update the rdo promote job
* upload the images via jenkins shell
* remove default publishers from the parent job
* --extra-var for current delorean hash

Change-Id: If2f355bc377a483a22de208eebfb1dace8ec2f95

diff --git a/jenkins-jobs/builders.yaml b/jenkins-jobs/builders.yaml
--- a/jenkins-jobs/builders.yaml
+++ b/jenkins-jobs/builders.yaml
@@ -77,6 +77,97 @@
 
                 exit $result
 
+- builder:
+    name: ksgen-builder-rdo-manager-promote
+    builders:
+        - shining-panda:
+            build-environment: virtualenv
+            python-version: system-CPython-2.7
+            nature: shell
+            clear: false
+            use-distribute: true
+            system-site-packages: false
+            ignore-exit-code: false
+            command: |
+                pip install -U ansible==1.9.2 > ansible_build; ansible --version
+
+                # install ksgen
+                pushd khaleesi/tools/ksgen
+                python setup.py install
+                popd
+
+                pushd khaleesi
+
+                cp ansible.cfg.example ansible.cfg
+                touch ssh.config.ansible
+                echo "" >> ansible.cfg
+                echo "[ssh_connection]" >> ansible.cfg
+                echo "ssh_args = -F ssh.config.ansible" >> ansible.cfg
+
+                # fetch dependent gating changes
+                if [ $GERRIT_CHANGE_COMMIT_MESSAGE ]; then
+                    ansible-playbook -i local_hosts -vv playbooks/depends-on.yml
+                fi
+
+                # generate config
+                ksgen --config-dir=settings generate \
+                    --provisioner=centosci \
+                    --provisioner-site=default \
+                    --provisioner-distro=centos \
+                    --provisioner-distro-version={provisioner-distro-version} \
+                    --provisioner-site-user=rdo \
+                    --product={product} \
+                    --product-version={product-version} \
+                    --product-version-build={pin} \
+                    --product-version-repo={product-version-repo} \
+                    --distro={distro} \
+                    --installer={installer} \
+                    --installer-deploy={installer-deploy} \
+                    --installer-env={installer-env} \
+                    --installer-images={installer-images} \
+                    --installer-network={network} \
+                    --installer-network-isolation={network-isolation} \
+                    --installer-network-variant={network-variant} \
+                    --installer-post_action={installer-post_action} \
+                    --installer-topology={installer-topology} \
+                    --installer-tempest={installer-tempest} \
+                    --workarounds=enabled \
+                    --extra-vars @../khaleesi-settings/hardware_environments/virt/network_configs/{network-isolation}/hw_settings.yml \
+                    --extra-vars product.repo.delorean_pin_version=$delorean_current_hash \
+                    ksgen_settings.yml
+
+                # get nodes and run test
+                set +e
+                #echo the delorean hash
+                echo $delorean_current_hash
+                anscmd="stdbuf -oL -eL ansible-playbook -vv --extra-vars @ksgen_settings.yml"
+
+                $anscmd -i local_hosts playbooks/full-job-no-test.yml
+                result=$?
+
+                pip install shyaml > shyaml_build.log
+                if [[ ` shyaml get-value installer.undercloud_image < ksgen_settings.yml` == 'save' ]]; then
+                    $anscmd -i hosts playbooks/installer/rdo-manager/fetch_images.yml
+                    # if job/test, and image_fetch were ok, upload images to centos artifacts
+                    echo $delorean_current_hash > $WORKSPACE/images/{product-version}/delorean/testing/delorean_hash
+                    rsync -av $WORKSPACE/images rdo@artifacts.ci.centos.org::rdo/
+                    rm -rf $WORKSPACE/images/{product-version}/
+                    result=$?
+                fi
+
+                infra_result=0
+                $anscmd -i hosts playbooks/collect_logs.yml &> collect_logs.txt || infra_result=1
+                $anscmd -i local_hosts playbooks/cleanup.yml &> cleanup.txt || infra_result=2
+
+                if [[ "$infra_result" != "0" && "$result" = "0" ]]; then
+                    # if the job/test was ok, but collect_logs/cleanup failed,
+                    # print out why the job is going to be marked as failed
+                    result=$infra_result
+                    cat collect_logs.txt
+                    cat cleanup.txt
+                fi
+                exit $result
+
 
 - builder:
     name: ksgen-builder-packstack
@@ -158,6 +249,88 @@
 
                 exit $result
 
+- builder:
+    name: ksgen-builder-packstack-promote
+    builders:
+        - shining-panda:
+            build-environment: virtualenv
+            python-version: system-CPython-2.7
+            nature: shell
+            clear: false
+            use-distribute: true
+            system-site-packages: false
+            ignore-exit-code: false
+            command: |
+                pip install -U ansible==1.9.2 > ansible_build; ansible --version
+
+                # install ksgen
+                pushd khaleesi/tools/ksgen
+                python setup.py install
+                popd
+
+                pushd khaleesi
+
+                cp ansible.cfg.example ansible.cfg
+                touch ssh.config.ansible
+                echo "" >> ansible.cfg
+                echo "[ssh_connection]" >> ansible.cfg
+                echo "ssh_args = -F ssh.config.ansible" >> ansible.cfg
+
+                # fetch dependent gating changes
+                if [ $GERRIT_CHANGE_COMMIT_MESSAGE ]; then
+                    ansible-playbook -i local_hosts -vv playbooks/depends-on.yml
+                fi
+
+                # generate config
+                ksgen --config-dir=settings generate \
+                    --provisioner=centosci \
+                    --provisioner-site=default \
+                    --provisioner-distro={provisioner-distro} \
+                    --provisioner-distro-version={provisioner-distro-version} \
+                    --provisioner-site-user=rdo \
+                    --provisioner-topology=all-in-one \
+                    --product={product} \
+                    --product-version={product-version} \
+                    --product-version-repo={product-version-repo} \
+                    --product-version-build={pin} \
+                    --distro={distro} \
+                    --installer={installer} \
+                    --installer-network={network} \
+                    --installer-messaging=none \
+                    --installer-config=no_change \
+                    --workarounds=enabled \
+                    --extra-vars @../khaleesi-settings/hardware_environments/virt_default/hw_settings.yml \
+                    --extra-vars product.repo.delorean_pin_version=$delorean_current_hash \
+                    ksgen_settings.yml
+
+
+                # get nodes and run test
+                set +e
+                #echo the delorean hash
+                echo $delorean_current_hash
+                anscmd="stdbuf -oL -eL ansible-playbook -vv --extra-vars @ksgen_settings.yml"
+
+                $anscmd -i local_hosts playbooks/full-job-no-test.yml
+                result=$?
+
+                if [[ $result == 0 ]]; then
+                    $anscmd -i hosts playbooks/post-deploy/packstack/validate-packstack-aio.yml
+                    result=$?
+                fi
+
+                infra_result=0
+                $anscmd -i hosts playbooks/collect_logs.yml &> collect_logs.txt || infra_result=1
+                $anscmd -i local_hosts playbooks/cleanup.yml &> cleanup.txt || infra_result=2
+
+                if [[ "$infra_result" != "0" && "$result" = "0" ]]; then
+                    # if the job/test was ok, but collect_logs/cleanup failed,
+                    # print out why the job is going to be marked as failed
+                    result=$infra_result
+                    cat collect_logs.txt
+                    cat cleanup.txt
+                fi
+
+                exit $result
 
 - builder:
     name: ksgen-builder-rdo-manager-feature-virthost
