wait_for_ssh: fix hanging on stdin with pseudotty
usage of -tt with timeout wrapper causes ssh to hang
in same cases (when there is no tty during wait_for_ssh execution)
due to pseudo-tty messing with it, by enforcing < /dev/null
it seems to get fixed.

this also splits get-original boottime and do-reboot commands
to distinguish the case there is issue with rebooting itself
from the case when we start with un-sshable host.

Change-Id: Ie9b9e1d89797a0b341b7da8b6d7bba797f15104a

diff --git a/library/wait_for_ssh b/library/wait_for_ssh
--- a/library/wait_for_ssh
+++ b/library/wait_for_ssh
@@ -97,7 +97,7 @@ log_known_rc() {
     esac
 }
 parseboot() {
-    sed -nr 's/^boottime=([0-9]+)$/\1/p' <<<"$1"
+    sed -nr 's/^boottime=([0-9]+)$/\1/p' <<<"$1";
 }
 datefmt() { TZ=UTC date --date="@$1"; }
 
@@ -129,7 +129,7 @@ delay=${delay:-0.3}           # how long to wait between retrying ssh (low is be
 conntimeout=${conntimeout:-7} # (soft) timeout for ssh connection
 connkill=${connkill:-10}       # hard timeout for ssh connection
 ssh_opts="${ssh_opts:-}"
-ssh_opts="$ssh_opts -vvvv -tt"
+ssh_opts="$ssh_opts -vvvv -n"
 
 # basic sanity check of options
 [[ $connkill -gt $timeout ]] && connkill=$timeout
@@ -161,7 +161,7 @@ ssh="$ssh -o UserKnownHostsFile=/dev/null";
 
 # snippets for commands used via ssh
 cmd_boottime="cat /proc/uptime; echo \"boottime=\$(( \$(date +%s) - \$(cat /proc/uptime | sed s/[.].*//) ))\""
-cmd_reboot="sudo shutdown -r now"
+cmd_reboot="sudo nohup bash -c 'sleep 1; shutdown -r now' < /dev/null &>> /tmp/w4s.log"
 
 
 
@@ -171,16 +171,22 @@ if $reboot_first; then
     CHANGED="true"
     echo "Rebooting host $host ..."
 
-    # info about this construction see below
-    output=$(timeout -s KILL ${connkill}s $ssh  "$cmd_boottime; $cmd_reboot" 2> >(log_debug))
+    # fetch the boottime first
+    output=$(timeout -s KILL ${connkill}s $ssh  "$cmd_boottime" 2> >(log_debug) < /dev/null)
     last_rc=$?
     log_debug "sshout: $output"
     log_known_rc $last_rc
     oldboottime="$(parseboot "$output")"
     if [[ -z "$oldboottime" ]]; then
-        echo "Seems ssh for rebooting failed!"
+        echo "Failed to ssh before reboot - couldn't obtain original boottime."
         finish $E_REBOOTFAILED
     fi
+
+    output=$(timeout -s KILL ${connkill}s $ssh -tt "$cmd_reboot" 2> >(log_debug) < /dev/null)
+    last_rc=$?
+    log_debug "sshout: $output"
+    log_known_rc $last_rc
+    # we ignore any nonzero rc, due to connection possibly being broken by restart
 
     echo "Going to wait for reboot, which means boottime > $(datefmt $oldboottime)."
 else
@@ -212,7 +218,7 @@ while true; do
     # - be wrapped in killing-timeout (to not hang for any reason)
     # - capture possible boottime output in variable
     # - redirect any stderr content to log_debug function (whatever if it ignores or prints it out (-v arg used))
-    output="$(timeout -s KILL ${connkill}s $ssh  "$cmd_boottime" 2> >(log_debug))"
+    output="$(timeout -s KILL ${connkill}s $ssh  "$cmd_boottime" 2> >(log_debug) < /dev/null)"
     last_rc=$?
     log_debug "sshout: $boottime"
     log_known_rc $last_rc
