wait_for_ssh: warn when the path is not absolute
As ansible modules are being executed in different
pwd (in tmp) even on localhost, we do require
absolute path to the keyfile.

When the wait_for_ssh is going to fail due
to that keyfile is not valid file,
check if the 'absolute' path would be different,
and if so propose to the user that this may the reason.

As this seems to be quite common mistake.

Change-Id: If5ec3f6d94a34c510c6e333ac88638ea47f92a7a

diff --git a/library/wait_for_ssh b/library/wait_for_ssh
--- a/library/wait_for_ssh
+++ b/library/wait_for_ssh
@@ -148,7 +148,10 @@ fi
 [[ ! -z "$user" ]] && ssh_opts="$ssh_opts -o User=$user"
 if [[ ! -z "$key" ]]; then
     if [[ ! -f "$key" ]]; then
-        echo "Unable to read keyfile $key!" >&2
+        echo "Unable to read keyfile '$key'!" >&2
+        if [[ "$key" != "$(readlink -f "$key")" ]]; then
+            echo "Seems you did not specified full absolute path to the key." >&2
+        fi
         finish $E_MISCONF
     fi
     ssh_opts="$ssh_opts -i $key"
